### ISSUE TITLE
How to create a read more button for a post? I mean how to only show a part of posts and click "read more" to read all?

### ISSUE THREAD

**Issue by truongduyng** [yulijia/freshman21#1]

**Comment by sunxianchao** [comment]
when run jekyll serve show error：
Liquid Exception: Included file '_includes/JB/setup' not found in _posts/2012-04-01-python_1.md/#excerpt
jekyll 2.1.1 | Error:  Included file '_includes/JB/setup' not found

**Comment by yulijia** [comment]
Hi, @sunxianchao 

I don't use Jekyll Bootstrap in this theme and don't know how to reproduce your bug.
I also checked your repository and blog, it seems the problem have already fixed.  Let me know if there is anything I can do to help. 
Please delete the [author picture](https://i.imgur.com/15BT1.jpg) in your blog. This picture is copyright reserved.

**Comment by yulijia** [comment]
Hi, @truongduyng 

Freshman21 theme doesn't support "read more" mode. However, you can fix this problem by create post.summary, please see [this article](http://yulijia.net/freshman21/howto/2015/01/18/how-to-create-post-summary.html). 

In a short, using the new [index.html](https://gist.github.com/yulijia/2f865b78a28bfe9e0a81#file-index-html) to instead of the default index.html, and make sure all your articles have a **summary** in the markdown file header. Then you get the "read more" mode.

**Comment by truongduyng** [comment]
wow, greate theme and article!. Thank you very much.

**Comment by yulijia** [comment]
Hi, @truongduyng 

Thanks for you reply. I upload the readmore version to my repository, you can copy this version by using 

```
git clone --branch readmore https://github.com/yulijia/freshman21.git
```
