### ISSUE TITLE
Google search didn't work properly.

### ISSUE THREAD

**Issue by dbarobin** [yulijia/freshman21#13]
Thanks for adding Google search feature. I've tried to add full-text search feature via `jekyll-lunr-js-search`, but failed. Jekyll by GitHub don't support this plugin.

I add Goole search by myself according to your code. But it didn't work properly. I add hidden form parameter which is called **site**, yet I input search content, the results that provided by Google did't display the content of my own website. That is to say, the hidden form parameter site did't accept by Google search url.

I'm looking forward to fix this bug. Thanks.

Robin

**Comment by yulijia** [comment]
Hi, thanks for the bug report. I have tested the search box when upload the new features to the website, It used to work well. Due to [Google search engine update at last week](http://www.wired.com/2015/04/googles-search-change-isnt-mobilegeddon-shows-google-works/), the simple search box with non-JavaScript does not work any more. 

To fix the bug, I have to include a new JS file. You can find more detail at [here](https://github.com/yulijia/freshman21/commit/271e6664f01b45c231dd56fa2f4dfde75545438a)
