### ISSUE TITLE
How to custom navigation?

### ISSUE THREAD

**Issue by dbarobin** [yulijia/freshman21#7]
I found an interesting thing. When I added a `markdown file` in the root of my GitHub Pages repo, the title of markdown was placed in the **navigation** automatically. Besides, all of navigation was placed according to the order of initial character of each words.

My question is, how to custom navigation? Any order, any words?

Thanks!

Sincerely,
Robin

**Comment by yulijia** [comment]
To re-order the navigation tags, please change the markdown file name.

On this theme, I use aahome.md to instead of home.md, you can see the home tag bypassing other tags ahead of it.

Rename all markdown file by alphabetical list, you can get the order you wanted. 
For example:
<code>
a_home.md 
b_about.md
c_tags.md
......
</code>

**Comment by dbarobin** [comment]
Got it, Thanks!
