### ISSUE TITLE
Add feature of search?

### ISSUE THREAD

**Issue by dbarobin** [yulijia/freshman21#8]
I am looking forward to add search feature, thanks. Of course, I will try it by myself.

Sincerely,
Robin

**Comment by yulijia** [comment]
Jekyll provides [Search Plugins](https://github.com/PascalW/jekyll_indextank) , try use it.

Because I don't want to include so many JS script in this theme, I remove search engine and won't add it in the future.

By the way, you can delete the MathJax JS in the [head.html](https://github.com/dbarobin/dbarobin.github.io/blob/master/_includes/head.html) if you don't need write any mathematical formula.

**Comment by dbarobin** [comment]
As for me, search feature is necessary. I'll try it. Thanks!
